package io.github.jerryt92.jrag.mapper.mgb;

import io.github.jerryt92.jrag.po.mgb.ChatContextRecord;
import io.github.jerryt92.jrag.po.mgb.ChatContextRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ChatContextRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    long countByExample(ChatContextRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    int deleteByExample(ChatContextRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String contextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    int insert(ChatContextRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    int insertSelective(ChatContextRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    List<ChatContextRecord> selectByExample(ChatContextRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    ChatContextRecord selectByPrimaryKey(String contextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatContextRecord record, @Param("example") ChatContextRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatContextRecord record, @Param("example") ChatContextRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatContextRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatContextRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<ChatContextRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_record
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<ChatContextRecord> list, @Param("selective") ChatContextRecord.Column ... selective);
}