package io.github.jerryt92.jrag.mapper.mgb;

import io.github.jerryt92.jrag.po.mgb.MarkdownFileRelTextChunkPoExample;
import io.github.jerryt92.jrag.po.mgb.MarkdownFileRelTextChunkPoKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MarkdownFileRelTextChunkPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    long countByExample(MarkdownFileRelTextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    int deleteByExample(MarkdownFileRelTextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(MarkdownFileRelTextChunkPoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    int insert(MarkdownFileRelTextChunkPoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    int insertSelective(MarkdownFileRelTextChunkPoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    List<MarkdownFileRelTextChunkPoKey> selectByExample(MarkdownFileRelTextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarkdownFileRelTextChunkPoKey record, @Param("example") MarkdownFileRelTextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarkdownFileRelTextChunkPoKey record, @Param("example") MarkdownFileRelTextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<MarkdownFileRelTextChunkPoKey> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<MarkdownFileRelTextChunkPoKey> list, @Param("selective") MarkdownFileRelTextChunkPoKey.Column ... selective);
}