package io.github.jerryt92.jrag.mapper.mgb;

import io.github.jerryt92.jrag.po.mgb.MarkdownFilePo;
import io.github.jerryt92.jrag.po.mgb.MarkdownFilePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MarkdownFilePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    long countByExample(MarkdownFilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    int deleteByExample(MarkdownFilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    int insert(MarkdownFilePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    int insertSelective(MarkdownFilePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    List<MarkdownFilePo> selectByExample(MarkdownFilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    MarkdownFilePo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarkdownFilePo record, @Param("example") MarkdownFilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarkdownFilePo record, @Param("example") MarkdownFilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarkdownFilePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarkdownFilePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<MarkdownFilePo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<MarkdownFilePo> list, @Param("selective") MarkdownFilePo.Column ... selective);
}