package io.github.jerryt92.jrag.mapper.mgb;

import io.github.jerryt92.jrag.po.mgb.PropertiesPo;
import io.github.jerryt92.jrag.po.mgb.PropertiesPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PropertiesPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    long countByExample(PropertiesPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    int deleteByExample(PropertiesPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String propertyName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    int insert(PropertiesPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    int insertSelective(PropertiesPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    List<PropertiesPo> selectByExample(PropertiesPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    PropertiesPo selectByPrimaryKey(String propertyName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PropertiesPo record, @Param("example") PropertiesPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PropertiesPo record, @Param("example") PropertiesPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PropertiesPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PropertiesPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<PropertiesPo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_properties
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<PropertiesPo> list, @Param("selective") PropertiesPo.Column ... selective);
}