package io.github.jerryt92.jrag.mapper.mgb;

import io.github.jerryt92.jrag.po.mgb.TextChunkPo;
import io.github.jerryt92.jrag.po.mgb.TextChunkPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TextChunkPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    long countByExample(TextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int deleteByExample(TextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int insert(TextChunkPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int insertSelective(TextChunkPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    List<TextChunkPo> selectByExampleWithBLOBs(TextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    List<TextChunkPo> selectByExample(TextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    TextChunkPo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TextChunkPo record, @Param("example") TextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TextChunkPo record, @Param("example") TextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TextChunkPo record, @Param("example") TextChunkPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TextChunkPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TextChunkPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TextChunkPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<TextChunkPo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<TextChunkPo> list, @Param("selective") TextChunkPo.Column ... selective);
}