package io.github.jerrt92.jrag.mapper.mgb;

import io.github.jerrt92.jrag.po.mgb.ChatContextItem;
import io.github.jerrt92.jrag.po.mgb.ChatContextItemExample;
import io.github.jerrt92.jrag.po.mgb.ChatContextItemKey;
import io.github.jerrt92.jrag.po.mgb.ChatContextItemWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ChatContextItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    long countByExample(ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int deleteByExample(ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ChatContextItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int insert(ChatContextItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int insertSelective(ChatContextItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    List<ChatContextItemWithBLOBs> selectByExampleWithBLOBs(ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    List<ChatContextItem> selectByExample(ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    ChatContextItemWithBLOBs selectByPrimaryKey(ChatContextItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatContextItemWithBLOBs record, @Param("example") ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ChatContextItemWithBLOBs record, @Param("example") ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatContextItem record, @Param("example") ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatContextItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ChatContextItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatContextItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<ChatContextItemWithBLOBs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<ChatContextItemWithBLOBs> list, @Param("selective") ChatContextItemWithBLOBs.Column ... selective);
}