package io.github.jerrt92.jrag.mapper.mgb;

import io.github.jerrt92.jrag.po.mgb.EmbeddingsItemPo;
import io.github.jerrt92.jrag.po.mgb.EmbeddingsItemPoExample;
import io.github.jerrt92.jrag.po.mgb.EmbeddingsItemPoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmbeddingsItemPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    long countByExample(EmbeddingsItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int deleteByExample(EmbeddingsItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int insert(EmbeddingsItemPoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int insertSelective(EmbeddingsItemPoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    List<EmbeddingsItemPoWithBLOBs> selectByExampleWithBLOBs(EmbeddingsItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    List<EmbeddingsItemPo> selectByExample(EmbeddingsItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    EmbeddingsItemPoWithBLOBs selectByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmbeddingsItemPoWithBLOBs record, @Param("example") EmbeddingsItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EmbeddingsItemPoWithBLOBs record, @Param("example") EmbeddingsItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmbeddingsItemPo record, @Param("example") EmbeddingsItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmbeddingsItemPoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EmbeddingsItemPoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmbeddingsItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<EmbeddingsItemPoWithBLOBs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<EmbeddingsItemPoWithBLOBs> list, @Param("selective") EmbeddingsItemPoWithBLOBs.Column ... selective);
}