package io.github.jerryt92.jrag.po.mgb;

import java.util.ArrayList;
import java.util.Arrays;

public class ChatContextItem extends ChatContextItemKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.chat_role
     *
     * @mbg.generated
     */
    private Integer chatRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.feedback
     *
     * @mbg.generated
     */
    private Integer feedback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.add_time
     *
     * @mbg.generated
     */
    private Long addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.chat_role
     *
     * @return the value of chat_context_item.chat_role
     *
     * @mbg.generated
     */
    public Integer getChatRole() {
        return chatRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.chat_role
     *
     * @param chatRole the value for chat_context_item.chat_role
     *
     * @mbg.generated
     */
    public void setChatRole(Integer chatRole) {
        this.chatRole = chatRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.feedback
     *
     * @return the value of chat_context_item.feedback
     *
     * @mbg.generated
     */
    public Integer getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.feedback
     *
     * @param feedback the value for chat_context_item.feedback
     *
     * @mbg.generated
     */
    public void setFeedback(Integer feedback) {
        this.feedback = feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.add_time
     *
     * @return the value of chat_context_item.add_time
     *
     * @mbg.generated
     */
    public Long getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.add_time
     *
     * @param addTime the value for chat_context_item.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Long addTime) {
        this.addTime = addTime;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public enum Column {
        contextId("context_id", "contextId", "VARCHAR", false),
        messageIndex("message_index", "messageIndex", "INTEGER", false),
        chatRole("chat_role", "chatRole", "INTEGER", false),
        feedback("feedback", "feedback", "INTEGER", false),
        addTime("add_time", "addTime", "BIGINT", false),
        content("content", "content", "LONGVARCHAR", false),
        toolCallProcess("tool_call_process", "toolCallProcess", "LONGVARCHAR", false),
        ragInfos("rag_infos", "ragInfos", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}