package io.github.jerryt92.jrag.po.mgb;

import java.util.ArrayList;
import java.util.Arrays;

public class EmbeddingsItemPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embeddings_item.hash
     *
     * @mbg.generated
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embeddings_item.embedding_model
     *
     * @mbg.generated
     */
    private String embeddingModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embeddings_item.embedding_provider
     *
     * @mbg.generated
     */
    private String embeddingProvider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embeddings_item.check_embedding_hash
     *
     * @mbg.generated
     */
    private String checkEmbeddingHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embeddings_item.text_chunk_id
     *
     * @mbg.generated
     */
    private String textChunkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embeddings_item.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embeddings_item.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embeddings_item.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embeddings_item.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embeddings_item.hash
     *
     * @return the value of embeddings_item.hash
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embeddings_item.hash
     *
     * @param hash the value for embeddings_item.hash
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embeddings_item.embedding_model
     *
     * @return the value of embeddings_item.embedding_model
     *
     * @mbg.generated
     */
    public String getEmbeddingModel() {
        return embeddingModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embeddings_item.embedding_model
     *
     * @param embeddingModel the value for embeddings_item.embedding_model
     *
     * @mbg.generated
     */
    public void setEmbeddingModel(String embeddingModel) {
        this.embeddingModel = embeddingModel == null ? null : embeddingModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embeddings_item.embedding_provider
     *
     * @return the value of embeddings_item.embedding_provider
     *
     * @mbg.generated
     */
    public String getEmbeddingProvider() {
        return embeddingProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embeddings_item.embedding_provider
     *
     * @param embeddingProvider the value for embeddings_item.embedding_provider
     *
     * @mbg.generated
     */
    public void setEmbeddingProvider(String embeddingProvider) {
        this.embeddingProvider = embeddingProvider == null ? null : embeddingProvider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embeddings_item.check_embedding_hash
     *
     * @return the value of embeddings_item.check_embedding_hash
     *
     * @mbg.generated
     */
    public String getCheckEmbeddingHash() {
        return checkEmbeddingHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embeddings_item.check_embedding_hash
     *
     * @param checkEmbeddingHash the value for embeddings_item.check_embedding_hash
     *
     * @mbg.generated
     */
    public void setCheckEmbeddingHash(String checkEmbeddingHash) {
        this.checkEmbeddingHash = checkEmbeddingHash == null ? null : checkEmbeddingHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embeddings_item.text_chunk_id
     *
     * @return the value of embeddings_item.text_chunk_id
     *
     * @mbg.generated
     */
    public String getTextChunkId() {
        return textChunkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embeddings_item.text_chunk_id
     *
     * @param textChunkId the value for embeddings_item.text_chunk_id
     *
     * @mbg.generated
     */
    public void setTextChunkId(String textChunkId) {
        this.textChunkId = textChunkId == null ? null : textChunkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embeddings_item.description
     *
     * @return the value of embeddings_item.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embeddings_item.description
     *
     * @param description the value for embeddings_item.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embeddings_item.create_time
     *
     * @return the value of embeddings_item.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embeddings_item.create_time
     *
     * @param createTime the value for embeddings_item.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embeddings_item.update_time
     *
     * @return the value of embeddings_item.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embeddings_item.update_time
     *
     * @param updateTime the value for embeddings_item.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embeddings_item.create_user_id
     *
     * @return the value of embeddings_item.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embeddings_item.create_user_id
     *
     * @param createUserId the value for embeddings_item.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public enum Column {
        hash("hash", "hash", "CHAR", false),
        embeddingModel("embedding_model", "embeddingModel", "VARCHAR", false),
        embeddingProvider("embedding_provider", "embeddingProvider", "VARCHAR", false),
        checkEmbeddingHash("check_embedding_hash", "checkEmbeddingHash", "VARCHAR", false),
        textChunkId("text_chunk_id", "textChunkId", "CHAR", false),
        description("description", "description", "VARCHAR", false),
        createTime("create_time", "createTime", "BIGINT", false),
        updateTime("update_time", "updateTime", "BIGINT", false),
        createUserId("create_user_id", "createUserId", "VARCHAR", false),
        text("text", "text", "LONGVARCHAR", true),
        embedding("embedding", "embedding", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}