package io.github.jerryt92.jrag.po.mgb;

import java.util.ArrayList;
import java.util.Arrays;

public class EmbeddingsItemPoWithBLOBs extends EmbeddingsItemPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embeddings_item.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embeddings_item.embedding
     *
     * @mbg.generated
     */
    private String embedding;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embeddings_item.text
     *
     * @return the value of embeddings_item.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embeddings_item.text
     *
     * @param text the value for embeddings_item.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embeddings_item.embedding
     *
     * @return the value of embeddings_item.embedding
     *
     * @mbg.generated
     */
    public String getEmbedding() {
        return embedding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embeddings_item.embedding
     *
     * @param embedding the value for embeddings_item.embedding
     *
     * @mbg.generated
     */
    public void setEmbedding(String embedding) {
        this.embedding = embedding == null ? null : embedding.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public enum Column {
        hash("hash", "hash", "CHAR", false),
        embeddingModel("embedding_model", "embeddingModel", "VARCHAR", false),
        embeddingProvider("embedding_provider", "embeddingProvider", "VARCHAR", false),
        checkEmbeddingHash("check_embedding_hash", "checkEmbeddingHash", "VARCHAR", false),
        textChunkId("text_chunk_id", "textChunkId", "CHAR", false),
        description("description", "description", "VARCHAR", false),
        createTime("create_time", "createTime", "BIGINT", false),
        updateTime("update_time", "updateTime", "BIGINT", false),
        createUserId("create_user_id", "createUserId", "VARCHAR", false),
        text("text", "text", "LONGVARCHAR", true),
        embedding("embedding", "embedding", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table embeddings_item
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}