package io.github.jerryt92.jrag.po.mgb;

import java.util.ArrayList;
import java.util.List;

public class EmbeddingsItemPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    protected Integer rows;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public EmbeddingsItemPoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public EmbeddingsItemPoExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public EmbeddingsItemPoExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public EmbeddingsItemPoExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHashIsNull() {
            addCriterion("hash is null");
            return (Criteria) this;
        }

        public Criteria andHashIsNotNull() {
            addCriterion("hash is not null");
            return (Criteria) this;
        }

        public Criteria andHashEqualTo(String value) {
            addCriterion("hash =", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashNotEqualTo(String value) {
            addCriterion("hash <>", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashGreaterThan(String value) {
            addCriterion("hash >", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashGreaterThanOrEqualTo(String value) {
            addCriterion("hash >=", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashLessThan(String value) {
            addCriterion("hash <", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashLessThanOrEqualTo(String value) {
            addCriterion("hash <=", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashLike(String value) {
            addCriterion("hash like", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashNotLike(String value) {
            addCriterion("hash not like", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashIn(List<String> values) {
            addCriterion("hash in", values, "hash");
            return (Criteria) this;
        }

        public Criteria andHashNotIn(List<String> values) {
            addCriterion("hash not in", values, "hash");
            return (Criteria) this;
        }

        public Criteria andHashBetween(String value1, String value2) {
            addCriterion("hash between", value1, value2, "hash");
            return (Criteria) this;
        }

        public Criteria andHashNotBetween(String value1, String value2) {
            addCriterion("hash not between", value1, value2, "hash");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelIsNull() {
            addCriterion("embedding_model is null");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelIsNotNull() {
            addCriterion("embedding_model is not null");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelEqualTo(String value) {
            addCriterion("embedding_model =", value, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelNotEqualTo(String value) {
            addCriterion("embedding_model <>", value, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelGreaterThan(String value) {
            addCriterion("embedding_model >", value, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelGreaterThanOrEqualTo(String value) {
            addCriterion("embedding_model >=", value, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelLessThan(String value) {
            addCriterion("embedding_model <", value, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelLessThanOrEqualTo(String value) {
            addCriterion("embedding_model <=", value, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelLike(String value) {
            addCriterion("embedding_model like", value, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelNotLike(String value) {
            addCriterion("embedding_model not like", value, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelIn(List<String> values) {
            addCriterion("embedding_model in", values, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelNotIn(List<String> values) {
            addCriterion("embedding_model not in", values, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelBetween(String value1, String value2) {
            addCriterion("embedding_model between", value1, value2, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingModelNotBetween(String value1, String value2) {
            addCriterion("embedding_model not between", value1, value2, "embeddingModel");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderIsNull() {
            addCriterion("embedding_provider is null");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderIsNotNull() {
            addCriterion("embedding_provider is not null");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderEqualTo(String value) {
            addCriterion("embedding_provider =", value, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderNotEqualTo(String value) {
            addCriterion("embedding_provider <>", value, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderGreaterThan(String value) {
            addCriterion("embedding_provider >", value, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderGreaterThanOrEqualTo(String value) {
            addCriterion("embedding_provider >=", value, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderLessThan(String value) {
            addCriterion("embedding_provider <", value, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderLessThanOrEqualTo(String value) {
            addCriterion("embedding_provider <=", value, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderLike(String value) {
            addCriterion("embedding_provider like", value, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderNotLike(String value) {
            addCriterion("embedding_provider not like", value, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderIn(List<String> values) {
            addCriterion("embedding_provider in", values, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderNotIn(List<String> values) {
            addCriterion("embedding_provider not in", values, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderBetween(String value1, String value2) {
            addCriterion("embedding_provider between", value1, value2, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andEmbeddingProviderNotBetween(String value1, String value2) {
            addCriterion("embedding_provider not between", value1, value2, "embeddingProvider");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdIsNull() {
            addCriterion("text_chunk_id is null");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdIsNotNull() {
            addCriterion("text_chunk_id is not null");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdEqualTo(String value) {
            addCriterion("text_chunk_id =", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdNotEqualTo(String value) {
            addCriterion("text_chunk_id <>", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdGreaterThan(String value) {
            addCriterion("text_chunk_id >", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdGreaterThanOrEqualTo(String value) {
            addCriterion("text_chunk_id >=", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdLessThan(String value) {
            addCriterion("text_chunk_id <", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdLessThanOrEqualTo(String value) {
            addCriterion("text_chunk_id <=", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdLike(String value) {
            addCriterion("text_chunk_id like", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdNotLike(String value) {
            addCriterion("text_chunk_id not like", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdIn(List<String> values) {
            addCriterion("text_chunk_id in", values, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdNotIn(List<String> values) {
            addCriterion("text_chunk_id not in", values, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdBetween(String value1, String value2) {
            addCriterion("text_chunk_id between", value1, value2, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdNotBetween(String value1, String value2) {
            addCriterion("text_chunk_id not between", value1, value2, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Long value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Long value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Long value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Long value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Long> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Long> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Long value1, Long value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Long value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Long value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Long value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Long value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Long value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Long> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Long> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Long value1, Long value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Long value1, Long value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table embeddings_item
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table embeddings_item
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}