package io.github.jerryt92.jrag.po.mgb;

import java.util.ArrayList;
import java.util.Arrays;

public class MarkdownFileRelTextChunkPoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column markdown_file_rel_text_chunk.markdown_file_id
     *
     * @mbg.generated
     */
    private Integer markdownFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column markdown_file_rel_text_chunk.text_chunk_id
     *
     * @mbg.generated
     */
    private String textChunkId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column markdown_file_rel_text_chunk.markdown_file_id
     *
     * @return the value of markdown_file_rel_text_chunk.markdown_file_id
     *
     * @mbg.generated
     */
    public Integer getMarkdownFileId() {
        return markdownFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column markdown_file_rel_text_chunk.markdown_file_id
     *
     * @param markdownFileId the value for markdown_file_rel_text_chunk.markdown_file_id
     *
     * @mbg.generated
     */
    public void setMarkdownFileId(Integer markdownFileId) {
        this.markdownFileId = markdownFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column markdown_file_rel_text_chunk.text_chunk_id
     *
     * @return the value of markdown_file_rel_text_chunk.text_chunk_id
     *
     * @mbg.generated
     */
    public String getTextChunkId() {
        return textChunkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column markdown_file_rel_text_chunk.text_chunk_id
     *
     * @param textChunkId the value for markdown_file_rel_text_chunk.text_chunk_id
     *
     * @mbg.generated
     */
    public void setTextChunkId(String textChunkId) {
        this.textChunkId = textChunkId == null ? null : textChunkId.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public enum Column {
        markdownFileId("markdown_file_id", "markdownFileId", "INTEGER", false),
        textChunkId("text_chunk_id", "textChunkId", "CHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table markdown_file_rel_text_chunk
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}