package io.github.jerryt92.jrag.po.mgb;

import java.util.ArrayList;
import java.util.List;

public class MarkdownFileRelTextChunkPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    protected Integer rows;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public MarkdownFileRelTextChunkPoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public MarkdownFileRelTextChunkPoExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public MarkdownFileRelTextChunkPoExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public MarkdownFileRelTextChunkPoExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMarkdownFileIdIsNull() {
            addCriterion("markdown_file_id is null");
            return (Criteria) this;
        }

        public Criteria andMarkdownFileIdIsNotNull() {
            addCriterion("markdown_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andMarkdownFileIdEqualTo(Integer value) {
            addCriterion("markdown_file_id =", value, "markdownFileId");
            return (Criteria) this;
        }

        public Criteria andMarkdownFileIdNotEqualTo(Integer value) {
            addCriterion("markdown_file_id <>", value, "markdownFileId");
            return (Criteria) this;
        }

        public Criteria andMarkdownFileIdGreaterThan(Integer value) {
            addCriterion("markdown_file_id >", value, "markdownFileId");
            return (Criteria) this;
        }

        public Criteria andMarkdownFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("markdown_file_id >=", value, "markdownFileId");
            return (Criteria) this;
        }

        public Criteria andMarkdownFileIdLessThan(Integer value) {
            addCriterion("markdown_file_id <", value, "markdownFileId");
            return (Criteria) this;
        }

        public Criteria andMarkdownFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("markdown_file_id <=", value, "markdownFileId");
            return (Criteria) this;
        }

        public Criteria andMarkdownFileIdIn(List<Integer> values) {
            addCriterion("markdown_file_id in", values, "markdownFileId");
            return (Criteria) this;
        }

        public Criteria andMarkdownFileIdNotIn(List<Integer> values) {
            addCriterion("markdown_file_id not in", values, "markdownFileId");
            return (Criteria) this;
        }

        public Criteria andMarkdownFileIdBetween(Integer value1, Integer value2) {
            addCriterion("markdown_file_id between", value1, value2, "markdownFileId");
            return (Criteria) this;
        }

        public Criteria andMarkdownFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("markdown_file_id not between", value1, value2, "markdownFileId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdIsNull() {
            addCriterion("text_chunk_id is null");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdIsNotNull() {
            addCriterion("text_chunk_id is not null");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdEqualTo(String value) {
            addCriterion("text_chunk_id =", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdNotEqualTo(String value) {
            addCriterion("text_chunk_id <>", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdGreaterThan(String value) {
            addCriterion("text_chunk_id >", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdGreaterThanOrEqualTo(String value) {
            addCriterion("text_chunk_id >=", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdLessThan(String value) {
            addCriterion("text_chunk_id <", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdLessThanOrEqualTo(String value) {
            addCriterion("text_chunk_id <=", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdLike(String value) {
            addCriterion("text_chunk_id like", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdNotLike(String value) {
            addCriterion("text_chunk_id not like", value, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdIn(List<String> values) {
            addCriterion("text_chunk_id in", values, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdNotIn(List<String> values) {
            addCriterion("text_chunk_id not in", values, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdBetween(String value1, String value2) {
            addCriterion("text_chunk_id between", value1, value2, "textChunkId");
            return (Criteria) this;
        }

        public Criteria andTextChunkIdNotBetween(String value1, String value2) {
            addCriterion("text_chunk_id not between", value1, value2, "textChunkId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table markdown_file_rel_text_chunk
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}