package io.github.jerryt92.jrag.mapper;

import io.github.jerryt92.jrag.mapper.mgb.TextChunkPoMapper;
import io.github.jerryt92.jrag.po.mgb.TextChunkPo;
import io.github.jerryt92.jrag.po.mgb.TextChunkPoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface MyTextChunkPoMapper extends TextChunkPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_chunk
     *
     * @mbg.generated
     */
    List<TextChunkPo> selectByExampleWithBLOBsWithSearch(@Param("example") TextChunkPoExample example, @Param("search") String search);
}