package io.github.jerrt92.jrag.po.mgb;

import java.util.ArrayList;
import java.util.Arrays;

public class FilePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.full_file_name
     *
     * @mbg.generated
     */
    private String fullFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.suffix
     *
     * @mbg.generated
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.size
     *
     * @mbg.generated
     */
    private Long size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.md5
     *
     * @mbg.generated
     */
    private String md5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.sha1
     *
     * @mbg.generated
     */
    private String sha1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.upload_time
     *
     * @mbg.generated
     */
    private Long uploadTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.full_file_name
     *
     * @return the value of file.full_file_name
     *
     * @mbg.generated
     */
    public String getFullFileName() {
        return fullFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.full_file_name
     *
     * @param fullFileName the value for file.full_file_name
     *
     * @mbg.generated
     */
    public void setFullFileName(String fullFileName) {
        this.fullFileName = fullFileName == null ? null : fullFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.suffix
     *
     * @return the value of file.suffix
     *
     * @mbg.generated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.suffix
     *
     * @param suffix the value for file.suffix
     *
     * @mbg.generated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.path
     *
     * @return the value of file.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.path
     *
     * @param path the value for file.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.size
     *
     * @return the value of file.size
     *
     * @mbg.generated
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.size
     *
     * @param size the value for file.size
     *
     * @mbg.generated
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.md5
     *
     * @return the value of file.md5
     *
     * @mbg.generated
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.md5
     *
     * @param md5 the value for file.md5
     *
     * @mbg.generated
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.sha1
     *
     * @return the value of file.sha1
     *
     * @mbg.generated
     */
    public String getSha1() {
        return sha1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.sha1
     *
     * @param sha1 the value for file.sha1
     *
     * @mbg.generated
     */
    public void setSha1(String sha1) {
        this.sha1 = sha1 == null ? null : sha1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.upload_time
     *
     * @return the value of file.upload_time
     *
     * @mbg.generated
     */
    public Long getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.upload_time
     *
     * @param uploadTime the value for file.upload_time
     *
     * @mbg.generated
     */
    public void setUploadTime(Long uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table file
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        fullFileName("full_file_name", "fullFileName", "VARCHAR", false),
        suffix("suffix", "suffix", "VARCHAR", false),
        path("path", "path", "VARCHAR", true),
        size("size", "size", "BIGINT", true),
        md5("md5", "md5", "VARCHAR", false),
        sha1("sha1", "sha1", "CHAR", false),
        uploadTime("upload_time", "uploadTime", "BIGINT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table file
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table file
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table file
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table file
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table file
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table file
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table file
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table file
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table file
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table file
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table file
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table file
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table file
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table file
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table file
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table file
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table file
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}